server:
  port: 8082
spring:
  application:
    name: vwap-calculator
  rabbitmq:  
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
        default-requeue-rejected: false
  datasource:
    host: localhost
    port: 5432
    dbname: price-data-base
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbname}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update      
management:
  endpoints:
    web:
      exposure:
        include: "*"

# customize properties which will be used in the code
rabbitmq:
  exchange:
    name: price-data-exchange
  queue:
    name: price-data-queue
  routing:
    key: price-data-routing-key

external:
  api:
    endpoint: http://localhost:8081/external-resource/get-data